[package]
name = "distribution-test"
version = "0.1.0"
edition = "2024"

[dependencies]
casper-types = { version = "6.0.0"}
casper-engine-test-support = { version = "8.1.0" }


[[test]]
name = "vm_tests"
path = "tests/vm_tests.rs"
